export const GET_COMMODITY_LIST_REQUEST = "GET_COMMODITY_LIST_REQUEST";
export const GET_COMMODITY_LIST_SUCCESS = "GET_COMMODITY_LIST_SUCCESS";
export const GET_COMMODITY_LIST_FAIL = "GET_COMMODITY_LIST_FAIL";


export const GET_COMMODITY_REQUEST = "GET_COMMODITY_REQUEST";
export const GET_COMMODITY_SUCCESS = "GET_COMMODITY_SUCCESS";
export const GET_COMMODITY_FAIL = "GET_COMMODITY_FAIL";

