export const GET_SWIPER_IMAGE_LIST_REQUEST = "GET_SWIPER_IMAGE_LIST_REQUEST";
export const GET_SWIPER_IMAGE_LIST_SUCCESS = "GET_SWIPER_IMAGE_LIST_SUCCESS";
export const GET_SWIPER_IMAGE_LIST_FAIL = "GET_SWIPER_IMAGE_LIST_FAIL";


export const UPDATE_SWIPER_IMAGE_LIST_REQUEST = "UPDATE_SWIPER_IMAGE_LIST_REQUEST";
export const UPDATE_SWIPER_IMAGE_LIST_SUCCESS = "UPDATE_SWIPER_IMAGE_LIST_SUCCESS";
export const UPDATE_SWIPER_IMAGE_LIST_FAIL = "UPDATE_SWIPER_IMAGE_LIST_FAIL";

export const GET_HOTCASE_LIST_REQUEST = "GET_HOTCASE_LIST_REQUEST";
export const GET_HOTCASE_LIST_SUCCESS = "GET_HOTCASE_LIST_SUCCESS";
export const GET_HOTCASE_LIST_FAIL = "GET_HOTCASE_LIST_FAIL";

export const UPDATE_HOTCASE_LIST_REQUEST = "UPDATE_HOTCASE_LIST_REQUEST";
export const UPDATE_HOTCASE_LIST_SUCCESS = "UPDATE_HOTCASE_LIST_SUCCESS";
export const UPDATE_HOTCASE_LIST_FAIL = "UPDATE_HOTCASE_LIST_FAIL";

export const GET_SPECIAL_ACTIVITY_LIST_REQUEST = "GET_SPECIAL_ACTIVITY_LIST_REQUEST";
export const GET_SPECIAL_ACTIVITY_LIST_SUCCESS = "GET_SPECIAL_ACTIVITY_LIST_SUCCESS";
export const GET_SPECIAL_ACTIVITY_LIST_FAIL = "GET_SPECIAL_ACTIVITY_LIST_FAIL";

export const UPDATE_SPECIAL_ACTIVITY_LIST_ITEM_REQUEST = "UPDATE_SPECIAL_ACTIVITY_LIST_ITEM_REQUEST";
export const UPDATE_SPECIAL_ACTIVITY_LIST_ITEM_SUCCESS = "UPDATE_SPECIAL_ACTIVITY_LIST_ITEM_SUCCESS";
export const UPDATE_SPECIAL_ACTIVITY_LIST_ITEM_FAIL = "UPDATE_SPECIAL_ACTIVITY_LIST_ITEM_FAIL";

export const ADD_SPECIAL_ACTIVITY_LIST_ITEM_REQUEST = "ADD_SPECIAL_ACTIVITY_LIST_ITEM_REQUEST";
export const ADD_SPECIAL_ACTIVITY_LIST_ITEM_SUCCESS = "ADD_SPECIAL_ACTIVITY_LIST_ITEM_SUCCESS";
export const ADD_SPECIAL_ACTIVITY_LIST_ITEM_FAIL = "ADD_SPECIAL_ACTIVITY_LIST_ITEM_FAIL";

export const REMOVE_SPECIAL_ACTIVITY_LIST_ITEM_REQUEST = "REMOVE_SPECIAL_ACTIVITY_LIST_ITEM_REQUEST";
export const REMOVE_SPECIAL_ACTIVITY_LIST_ITEM_SUCCESS = "REMOVE_SPECIAL_ACTIVITY_LIST_ITEM_SUCCESS";
export const REMOVE_SPECIAL_ACTIVITY_LIST_ITEM_FAIL = "REMOVE_SPECIAL_ACTIVITY_LIST_ITEM_FAIL";
