export const LOGIN_IN_REQUEST = 'LOGIN_IN_REQUEST';
export const LOGIN_IN_SUCCESS = 'LOGIN_IN_SUCCESS';
export const LOGIN_IN_FAIL = 'LOGIN_IN_FAIL';

export const LOGIN_OUT_REQUEST = 'LOGIN_OUT_REQUEST';
export const LOGIN_OUT_SUCCESS = 'LOGIN_OUT_SUCCESS';
export const LOGIN_OUT_FAIL = 'LOGIN_OUT_FAIL';
//用户基本信息
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';





